/**
 * Which destinations have a capsule — the cheapest possible answer.
 *
 * WHY THIS IS A SEPARATE FILE WITH NO IMPORTS
 * -------------------------------------------
 * `resolveCapabilities` runs for every destination on every build, including
 * the twelve that have nothing. It has always short-circuited before touching
 * a single content module, and `qa:destination` asserts that. Asking the
 * capsule registry "do you have one?" would have imported the registry — and
 * with it the validator — for destinations that were about to be told they
 * have no content at all.
 *
 * So membership lives here: a list of strings, no imports, statically
 * readable. The registry with its lazy importers is only reached once this
 * list says there is something to reach for.
 *
 * PHASE 18 filled it with eight Indian destinations; PHASE 19 added four
 * global ones; PHASE B added Jaipur and Kyoto, which already held reviewed
 * research knowledge and had nothing catalogued to visit. All fourteen are
 * retrieved and generated by `scripts/capsules/`.
 *
 * A destination in this list may ALSO have published research knowledge. The
 * two are different ways of knowing a place and the capability model carries
 * both without either shadowing the other. Keep it sorted, and keep it in step with the
 * importer table in `index.ts` — `capsuleRegistryDrift()` reports a
 * disagreement, and `qa:content-framework` fails on one.
 */
export const CAPSULE_IDS: string[] = [
  "agra",
  "delhi",
  "goa",
  "hyderabad",
  "istanbul",
  "jaipur",
  "kochi",
  "kolkata",
  "kyoto",
  "mumbai",
  "new-york-city",
  "paris",
  "rome",
  "varanasi",
];

export function hasCapsuleId(destinationId: string): boolean {
  return CAPSULE_IDS.includes(destinationId);
}
